/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class AudioProcessorValueTreeStateDemoAudioProcessorEditor  : public AudioProcessorEditor,
                                                              public SliderListener,
                                                              public ButtonListener
{
public:
    AudioProcessorValueTreeStateDemoAudioProcessorEditor (AudioProcessorValueTreeStateDemoAudioProcessor&);
    ~AudioProcessorValueTreeStateDemoAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    void sliderValueChanged (Slider* sliderThatWasMoved) override;
    void buttonClicked (Button* buttonThatWasClicked) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    AudioProcessorValueTreeStateDemoAudioProcessor& processor;
    
    void createUI();
    void destroyUI();
    void resizeUI();
    
    /** UI ELEMENTES **/
    ScopedPointer<Slider> clipSlider;
    ScopedPointer<Label> clipLabel;
    ScopedPointer<Slider> bitsSlider;
    ScopedPointer<Label> bitsLabel;
    ScopedPointer<Slider> samplerateSlider;
    ScopedPointer<Label> samplerateLabel;
    ScopedPointer<Slider> levelSlider;
    ScopedPointer<Label> levelLabel;
    ScopedPointer<Slider> nonlinSlider;
    ScopedPointer<Label> nonlinLabel;
    ScopedPointer<Slider> postfiltSlider;
    ScopedPointer<Label> postfiltLabel;
    ScopedPointer<TextButton> nonlinmodeButton;
    ScopedPointer<TextButton> postfiltmodeButton;
    ScopedPointer<GroupComponent> groupComponent;
    ScopedPointer<TextButton> undoBtn;
    ScopedPointer<TextButton> redoBtn;
    ScopedPointer<Label> label;
    ScopedPointer<Label> actionText;
    /** UI ELEMENTES **/
    
    /** UI <> Parameters Listeners **/
    ScopedPointer<AudioProcessorValueTreeState::SliderAttachment> clipParamAttach, bitsParamAttach, samplerateParamAttach, levelParamAttach, nonlinParamAttach, postfiltParamAttach;
    ScopedPointer<AudioProcessorValueTreeState::ButtonAttachment> nonlinmodeParamAttach, postfiltmodeParamAttach;

    

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (AudioProcessorValueTreeStateDemoAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
