/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "WaveformComponent.h"


//==============================================================================
/**
*/
class WaveformPluginAudioProcessorEditor  : public AudioProcessorEditor,
                                            public ChangeListener
{
public:
    WaveformPluginAudioProcessorEditor (WaveformPluginAudioProcessor&);
    ~WaveformPluginAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
    
    void visibilityChanged() override;
    
    void changeListenerCallback (ChangeBroadcaster *source) override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    WaveformPluginAudioProcessor& processor;
    WaveformComponent waveformComponent;
    
    OpenGLContext _contextOpenGL;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (WaveformPluginAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
